# SPDX-License-Identifier: LGPL-3.0-only
{
    "name": "Southbrook Kitchen MRP",
    "summary": "Cut lists, hardware packages, and production packages for "
               "the Southbrook kitchen-MRP flow. Bridges the FreeCAD-rendered "
               "panel geometry to the shop floor and to the internal "
               "cutting/nesting division.",
    "description": """
Southbrook Kitchen MRP (Module 4)
==================================

Three first-class entities the rest of the platform writes to:

* ``sb.cutlist`` + ``sb.cutlist.line`` — the panel cut list for one MO,
  generated from the 7-panel formulas in shared/southbrook_dims. The
  FreeCAD bridge writes panel geometry into this; the nesting prep step
  (opticutter / Accucutt-style internal division) reads from it.
  Toe-kick is integrated into the side panels and therefore NEVER
  appears as a cut-list line — that contract is enforced by tests so a
  future refactor cannot silently change it.

* ``sb.hardware.package`` + ``sb.hardware.package.line`` — the resolved
  hardware pick list for one MO. Generated by calling
  ``env['southbrook.hardware.catalog'].resolve(...)`` from Module 3,
  which aggregates per_door + per_drawer + per_shelf + per_cabinet +
  per_family rules into one line per SKU.

* ``sb.production.package`` — bundles a cutlist + a hardware package +
  a state machine (draft → exported → nested → done) for the shop-floor
  handoff. The init doc Module 4 DoD says an MO produces a complete
  cutlist + hardware package — that's what generate_from_mo() does.

Nesting interface (the cutlist ↔ internal cutting/nesting division
contract, GAP-05 / SYN-02):

* ``sb.cutlist.to_nesting_envelope()`` returns a deterministic JSON
  payload the cutting/nesting division consumes.
* ``sb.cutlist.from_nesting_result(payload)`` accepts the nest result
  and flips state to ``nested`` plus stores yield + waste metadata.

M4 (catalog-wide BoM generator)
--------------------------------

* ``mrp.bom._southbrook_generate_catalog_boms()`` — walks every
  ``southbrook_is_cabinet=True`` product.template with no 'normal' BoM
  yet and CREATES one with real, non-empty ``bom_line_ids`` (panel
  materials + real Marathon hardware SKUs). Never mutates or deletes an
  existing BoM. Idempotent. Wired to a nightly ``ir.cron``
  (``cron_southbrook_catalog_bom_generator``) that can also be run
  manually from Settings > Technical > Automation > Scheduled Actions.
""",
    "author": "Southbrook Kitchens / OdooIQ",
    "license": "LGPL-3",
    "category": "Manufacturing",
    "version": "19.0.1.5.0",
    "depends": [
        "mrp",
        "sale",
        "southbrook_estimating",
        "southbrook_hardware_catalog",
        "southbrook_freecad_bridge",
        # QR foundation — qr.mixin for cutlist + hardware package.
        "southbrook_qr_kit",
        # MO form redesign (19.0.1.0.0): hard depend ONLY on the
        # base mrp form. southbrook_mrp_kitchen_workcenters /
        # southbrook_manufacturing_intelligence transitively depend
        # on this addon already, so declaring them here creates a
        # dependency loop and the upgrade is skipped silently. The
        # redesign inherits only mrp.mrp_production_form_view; the
        # x_sbk_* and x_mi_* fields are present on mrp.production
        # at runtime because those addons are installed on prod.
    ],
    "external_dependencies": {
        # Cabinet manufacturing label embeds a QR PNG via qrcode +
        # Pillow. Pre-installed on the Odoo 19 Debian image.
        "python": ["qrcode"],
    },
    "data": [
        "security/ir.model.access.csv",
        "views/sb_cutlist_views.xml",
        "views/sb_hardware_package_views.xml",
        "views/sb_production_package_views.xml",
        "views/southbrook_kitchen_mrp_menus.xml",
        "views/mrp_production_form_redesign.xml",
        "reports/cabinet_label_report.xml",
        "data/cron_catalog_bom_generator.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
