# SPDX-License-Identifier: LGPL-3.0-only
{
    "name": "Southbrook Kitchen MRP",
    "summary": "Cut lists, hardware packages, and production packages for "
               "the Southbrook kitchen-MRP flow. Bridges the FreeCAD-rendered "
               "panel geometry to the shop floor and to the internal "
               "cutting/nesting division.",
    "description": """
Southbrook Kitchen MRP (Module 4)
==================================

Three first-class entities the rest of the platform writes to:

* ``sb.cutlist`` + ``sb.cutlist.line`` — the panel cut list for one MO,
  generated from the 7-panel formulas in shared/southbrook_dims. The
  FreeCAD bridge writes panel geometry into this; the nesting prep step
  (opticutter / Accucutt-style internal division) reads from it.
  Toe-kick is integrated into the side panels and therefore NEVER
  appears as a cut-list line — that contract is enforced by tests so a
  future refactor cannot silently change it.

* ``sb.hardware.package`` + ``sb.hardware.package.line`` — the resolved
  hardware pick list for one MO. Generated by calling
  ``env['southbrook.hardware.catalog'].resolve(...)`` from Module 3,
  which aggregates per_door + per_drawer + per_shelf + per_cabinet +
  per_family rules into one line per SKU.

* ``sb.production.package`` — bundles a cutlist + a hardware package +
  a state machine (draft → exported → nested → done) for the shop-floor
  handoff. The init doc Module 4 DoD says an MO produces a complete
  cutlist + hardware package — that's what generate_from_mo() does.

Nesting interface (the cutlist ↔ internal cutting/nesting division
contract, GAP-05 / SYN-02):

* ``sb.cutlist.to_nesting_envelope()`` returns a deterministic JSON
  payload the cutting/nesting division consumes.
* ``sb.cutlist.from_nesting_result(payload)`` accepts the nest result
  and flips state to ``nested`` plus stores yield + waste metadata.
""",
    "author": "Southbrook Kitchens / OdooIQ",
    "license": "LGPL-3",
    "category": "Manufacturing",
    "version": "19.0.0.1.0",
    "depends": [
        "mrp",
        "southbrook_estimating",
        "southbrook_hardware_catalog",
        "southbrook_freecad_bridge",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/sb_cutlist_views.xml",
        "views/sb_hardware_package_views.xml",
        "views/sb_production_package_views.xml",
        "views/southbrook_kitchen_mrp_menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
