from . import test_config_bookmark
from . import test_create
from . import test_configuration_rules
from . import test_product
from . import test_product_attribute
from . import test_product_config
from . import test_saved_config
from . import test_session_gc
from . import test_stock_info
from . import test_wizard
