# SPDX-License-Identifier: LGPL-3.0-only
"""sb.hardware.package + sb.hardware.package.line — resolved hardware pick
list for one MO. Generated by calling
env['southbrook.hardware.catalog'].resolve(...) from Module 3."""
import logging
from typing import List, Tuple

from odoo import _, api, fields, models

_logger = logging.getLogger(__name__)


HARDWARE_PACKAGE_STATES = [
    ("draft", "Draft"),
    ("picked", "Picked / Reserved"),
    ("delivered", "Delivered to Assembly"),
]


class SbHardwarePackage(models.Model):
    _name = "sb.hardware.package"
    _description = "Southbrook Hardware Package"
    _order = "id desc"

    name = fields.Char(required=True, default=lambda self: _("New"))
    mo_id = fields.Many2one(
        comodel_name="mrp.production",
        string="Manufacturing Order",
        ondelete="cascade",
        index=True,
    )
    state = fields.Selection(
        HARDWARE_PACKAGE_STATES, default="draft", tracking=True, required=True,
    )
    line_ids = fields.One2many(
        comodel_name="sb.hardware.package.line",
        inverse_name="package_id",
        string="Hardware Lines",
    )
    line_count = fields.Integer(compute="_compute_line_count", store=True)
    has_pricing_pending = fields.Boolean(
        compute="_compute_has_pricing_pending", store=True,
    )

    @api.depends("line_ids")
    def _compute_line_count(self):
        for r in self:
            r.line_count = len(r.line_ids)

    @api.depends("line_ids.product_id.x_pricing_pending")
    def _compute_has_pricing_pending(self):
        for r in self:
            r.has_pricing_pending = any(
                ln.product_id.x_pricing_pending for ln in r.line_ids
            )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("name", _("New")) == _("New"):
                vals["name"] = self.env["ir.sequence"].next_by_code(
                    "sb.hardware.package"
                ) or _("New")
        return super().create(vals_list)

    @api.model
    def generate_lines_from_resolution(
        self,
        package,
        picks: List[Tuple],
    ):
        """Create sb.hardware.package.line records from a
        southbrook.hardware.catalog.resolve() output list of
        (product.product, qty) tuples."""
        Line = self.env["sb.hardware.package.line"]
        for product, qty in picks:
            if qty <= 0:
                continue
            Line.create({
                "package_id": package.id,
                "product_id": product.id,
                "qty": qty,
            })


class SbHardwarePackageLine(models.Model):
    _name = "sb.hardware.package.line"
    _description = "Southbrook Hardware Package Line"
    _order = "package_id, sequence, id"

    package_id = fields.Many2one(
        comodel_name="sb.hardware.package",
        ondelete="cascade",
        required=True,
        index=True,
    )
    sequence = fields.Integer(default=10)
    product_id = fields.Many2one(
        comodel_name="product.product",
        string="Hardware SKU",
        required=True,
        domain="[('x_hardware_category', '!=', False)]",
    )
    qty = fields.Integer(default=1, required=True)
    pricing_pending = fields.Boolean(
        related="product_id.x_pricing_pending", store=True,
    )
    hardware_category = fields.Selection(
        related="product_id.x_hardware_category", store=True,
    )
    brand_id = fields.Many2one(
        related="product_id.x_hardware_brand_id", store=True,
    )
