#!/usr/bin/env bash
# provision_tenant.sh — QNAP-SIDE ONLY
#
# Stand up a fresh Odoo 19 CE demo stack for a new KitchenForge tenant on the
# QNAP at /share/CACHEDEV3_DATA/Container/<slug>/. Codifies the operator recipe
# from memory file qnap_demo_stacks.md, including the gotchas that have bitten
# every prior tenant install:
#
#   1. `umask 077` left certs/config unreadable by Odoo UID:GID 100:101 — we
#      explicitly chmod after creation.
#   2. Caddy's `request_body` block MUST be multi-line; a one-liner triggers
#      an obscure unmarshalling error.
#   3. Odoo 19 container runs as 100:101; the mounted dirs must be chowned
#      to that pair or the container CrashLoopBackOffs writing pidfile.
#   4. Caddy snippet PER SITE — sharing a snippet between sites smears their
#      X-Forwarded-Host headers and Odoo refuses to log in.
#   5. Cold-install: `-i base --stop-after-init` BEFORE the addon -i call,
#      otherwise `ir.model.data.module` cardinality errors surface during the
#      first kitchenforge_core install.
#
# This script is idempotent: if /share/CACHEDEV3_DATA/Container/<slug>/ exists
# it bails out (use a different slug, or run cleanup_tenant.sh first).
#
# Run ON the QNAP shell (admin@192.168.68.108):
#   sudo /share/CACHEDEV3_DATA/scripts/provision_tenant.sh \
#     --slug myshop --admin-email ops@myshop.com --tier marathon_channel
#
# This is NOT meant to be run from a Mac. The script asserts the QNAP
# environment (system-docker path, /share/CACHEDEV3_DATA existence).

set -euo pipefail

# ---- defaults ----------------------------------------------------------
SLUG=""
ADMIN_EMAIL=""
TIER="direct"                                   # marathon_channel | direct | enterprise
ROOT="/share/CACHEDEV3_DATA"
CONTAINER_DIR_BASE="$ROOT/Container"
QNAP_DOCKER="$ROOT/.qpkg/container-station/bin/system-docker"
CADDY_DIR="$CONTAINER_DIR_BASE/alfacore-caddy"
CADDY_FILE="$CADDY_DIR/Caddyfile"

# ---- arg parse ---------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --slug)        SLUG="$2"; shift 2 ;;
    --admin-email) ADMIN_EMAIL="$2"; shift 2 ;;
    --tier)        TIER="$2"; shift 2 ;;
    -h|--help)     sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

log()  { printf "[provision] %s\n" "$*" >&2; }
fail() { printf "[provision] ERROR: %s\n" "$*" >&2; exit 1; }

# ---- environment asserts ----------------------------------------------
[[ -z "$SLUG" ]]         && fail "--slug is required"
[[ ! "$SLUG" =~ ^[a-z][a-z0-9_]{2,31}$ ]] && fail "slug must be lowercase [a-z0-9_], 3-32 chars (got: $SLUG)"
[[ -z "$ADMIN_EMAIL" ]]  && fail "--admin-email is required"
case "$TIER" in marathon_channel|direct|enterprise) ;; *) fail "--tier must be one of marathon_channel|direct|enterprise (got: $TIER)" ;; esac
[[ -d "$ROOT" ]]         || fail "$ROOT missing — are you running this on the QNAP?"
[[ -x "$QNAP_DOCKER" ]]  || fail "system-docker not at $QNAP_DOCKER — are you running this on the QNAP?"
[[ -f "$CADDY_FILE" ]]   || fail "expected shared Caddyfile at $CADDY_FILE — provision the alfacore-caddy stack first"

TENANT_DIR="$CONTAINER_DIR_BASE/$SLUG"
if [[ -e "$TENANT_DIR" ]]; then
  fail "$TENANT_DIR already exists — refusing to clobber. Choose a different slug or remove the dir."
fi

log "tenant=$SLUG  tier=$TIER  admin=$ADMIN_EMAIL"
log "target dir: $TENANT_DIR"

# ---- generate random POSTGRES_PASSWORD --------------------------------
# /dev/urandom -> 32 chars of [A-Za-z0-9]. tr is the busybox tr that ships
# with QTS — `tr -dc` is portable here.
PG_PASS=$(head -c 64 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 32)
[[ ${#PG_PASS} -eq 32 ]] || fail "failed to generate POSTGRES_PASSWORD"

# ---- directory tree ----------------------------------------------------
# umask 077 trap: QTS shells default to 022 but cron + some service hooks
# inherit 077, leaving these unreadable by the Odoo container user. Force
# 022 for the creation, then explicit chmod at the end.
saved_umask=$(umask)
umask 022

mkdir -p "$TENANT_DIR"/{addons,config,data,backups,caddy/certs}
mkdir -p "$TENANT_DIR/data/odoo"
mkdir -p "$TENANT_DIR/data/postgres"

log "wrote directory tree under $TENANT_DIR"

# ---- .env --------------------------------------------------------------
cat > "$TENANT_DIR/.env" <<EOF
# auto-generated by provision_tenant.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SLUG=$SLUG
TIER=$TIER
ADMIN_EMAIL=$ADMIN_EMAIL
POSTGRES_DB=$SLUG
POSTGRES_USER=odoo
POSTGRES_PASSWORD=$PG_PASS
ODOO_DB=$SLUG
EOF
chmod 600 "$TENANT_DIR/.env"

# ---- config/odoo.conf --------------------------------------------------
# dbfilter pinned to the slug — multi-tenant safety: even if someone creates
# a second DB on the same Postgres, this Odoo will only serve `^slug$`.
cat > "$TENANT_DIR/config/odoo.conf" <<EOF
[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = $PG_PASS
dbfilter = ^${SLUG}\$
admin_passwd = $(head -c 32 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 24)
proxy_mode = True
limit_time_cpu = 600
limit_time_real = 1200
workers = 2
max_cron_threads = 1
; logrotate ignored by Odoo 19 — external logrotate handles this per memory
; qnap_odoo_log_rotation.md
log_level = info
logfile = /var/log/odoo/odoo.log
EOF

# ---- docker-compose.yml -----------------------------------------------
# Network names per-tenant; alfacore-caddy reaches the odoo upstream by the
# tenant network attachment (we declare the network as external so Caddy can
# attach to it too).
cat > "$TENANT_DIR/docker-compose.yml" <<EOF
# auto-generated by provision_tenant.sh — DO NOT edit by hand, regenerate.
networks:
  ${SLUG}-net:
    name: ${SLUG}-net

volumes:
  ${SLUG}-pg:
  ${SLUG}-odoo:

services:
  db:
    image: postgres:16-alpine
    container_name: ${SLUG}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: \${POSTGRES_DB}
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    volumes:
      - ${SLUG}-pg:/var/lib/postgresql/data
    networks: [${SLUG}-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 6

  odoo:
    image: odoo:19
    container_name: ${SLUG}-odoo
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      USER: \${POSTGRES_USER}
      PASSWORD: \${POSTGRES_PASSWORD}
    volumes:
      - ${SLUG}-odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons:ro
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./data/odoo:/var/log/odoo
    networks: [${SLUG}-net]
    # 8069 stays internal — Caddy fronts it. No published port.
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8069/web/login\", timeout=5)'"]
      interval: 30s
      timeout: 8s
      retries: 5
      start_period: 60s
EOF

# ---- self-signed TLS cert ---------------------------------------------
# Caddy can do real ACME but for LAN-only access we ship a self-signed pair
# so the stack works air-gapped. Replace with `tls internal` for ACME-staging
# or remove the cert lines for production with real domain.
log "generating self-signed cert for ${SLUG}.local …"
openssl req -x509 -newkey rsa:2048 -nodes \
  -subj "/CN=${SLUG}.local/O=Southbrook/OU=KitchenForge" \
  -days 730 \
  -keyout "$TENANT_DIR/caddy/certs/${SLUG}.key" \
  -out    "$TENANT_DIR/caddy/certs/${SLUG}.crt" 2>/dev/null

# ---- Caddy snippet (PER SITE — never share between tenants) -----------
# Append-only to the shared Caddyfile. If the snippet already exists for this
# slug we bail (idempotency). The multi-line request_body block is mandatory
# — a one-liner triggers a Caddy "cannot unmarshal" error per memory.
if grep -q "^(${SLUG}_routes) {" "$CADDY_FILE"; then
  log "Caddy snippet for ${SLUG} already present — skipping append"
else
  log "appending Caddy snippet for ${SLUG}"
  cat >> "$CADDY_FILE" <<EOF

# === ${SLUG} (auto-generated $(date -u +%Y-%m-%d)) ===
(${SLUG}_routes) {
  # request_body MUST be multi-line — see memory: qnap_demo_stacks
  request_body {
    max_size 200MB
  }
  encode gzip zstd
  reverse_proxy ${SLUG}-odoo:8069 {
    header_up X-Forwarded-Host {host}
    header_up X-Forwarded-Proto {scheme}
    header_up X-Real-IP {remote_host}
  }
}

${SLUG}.local:9443 {
  tls /etc/caddy/certs/${SLUG}.crt /etc/caddy/certs/${SLUG}.key
  import ${SLUG}_routes
}
EOF
fi

# ---- chown to 100:101 (Odoo container UID:GID) ------------------------
log "chowning $TENANT_DIR to 100:101 (Odoo container user)…"
chown -R 100:101 "$TENANT_DIR/data" "$TENANT_DIR/addons" "$TENANT_DIR/config"
chmod -R o+rX     "$TENANT_DIR/addons" "$TENANT_DIR/config"
chmod -R go-rwx   "$TENANT_DIR/caddy/certs"
chmod 600         "$TENANT_DIR/caddy/certs/${SLUG}.key"
chmod 644         "$TENANT_DIR/caddy/certs/${SLUG}.crt"

umask "$saved_umask"

# ---- bring stack up ----------------------------------------------------
log "starting postgres + odoo …"
( cd "$TENANT_DIR" && "$QNAP_DOCKER" compose up -d )

log "waiting for postgres healthy …"
for i in $(seq 1 30); do
  state=$("$QNAP_DOCKER" inspect "${SLUG}-postgres" --format '{{.State.Health.Status}}' 2>/dev/null || echo none)
  echo "  pg tick $i: $state"
  [[ "$state" == "healthy" ]] && break
  sleep 5
done

# ---- attach to caddy network + reload caddy ---------------------------
# alfacore-caddy is on its own network; we attach ${SLUG}-net to it so the
# Caddyfile's `reverse_proxy ${SLUG}-odoo:8069` resolves.
if "$QNAP_DOCKER" network inspect "${SLUG}-net" >/dev/null 2>&1; then
  log "attaching alfacore-caddy to ${SLUG}-net …"
  "$QNAP_DOCKER" network connect "${SLUG}-net" alfacore-caddy 2>/dev/null || true
fi
log "reloading caddy …"
"$QNAP_DOCKER" exec alfacore-caddy caddy reload --config /etc/caddy/Caddyfile || \
  log "WARN: caddy reload failed — check $CADDY_FILE syntax"

# ---- cold init: base first, then kitchenforge --------------------------
# `-i base --stop-after-init` is the prophylactic step from memory:
# southbrook_cold_install_gaps.md — it materializes ir_module_module so the
# kitchenforge_core install doesn't trip ir.model.data.module foreign-key
# errors on a virgin DB.
log "cold-init: base …"
"$QNAP_DOCKER" exec "${SLUG}-odoo" \
  odoo -i base -d "$SLUG" --stop-after-init --no-http \
       --db_host=db --db_user=odoo --db_password="$PG_PASS"

log "cold-init: kitchenforge_core,kitchenforge_marathon,kitchenforge_saas …"
"$QNAP_DOCKER" exec "${SLUG}-odoo" \
  odoo -i kitchenforge_core,kitchenforge_marathon,kitchenforge_saas \
       -d "$SLUG" --stop-after-init --no-http \
       --db_host=db --db_user=odoo --db_password="$PG_PASS"

log "restarting odoo for ormcache reset …"
"$QNAP_DOCKER" restart "${SLUG}-odoo"

log "tenant $SLUG provisioned. Reachable at https://${SLUG}.local:9443/ "
log "  admin password stored in $TENANT_DIR/config/odoo.conf (admin_passwd)"
log "  postgres password stored in $TENANT_DIR/.env (POSTGRES_PASSWORD)"
log "done."
