# SPDX-License-Identifier: LGPL-3.0-only
from . import test_m1_master_data
from . import test_m1_workcenter_fields
from . import test_m2_operation_templates
from . import test_m3_quality_and_downtime
from . import test_m4_production_and_routing
from . import test_asbuilt_pg_backrefs
from . import test_w011_form_open_scan_log
from . import test_w018_defect_context_echo
from . import test_w042_asbuilt_lot_snapshot
from . import test_w055_mo_qr_resolve
from . import test_w014_tablet_kanban
from . import test_w026_traveler_richness
from . import test_w043_reinspection_after_rework
from . import test_w044_operator_attribution
from . import test_w049_shift_attribution
from . import test_w054_my_time_visibility
from . import test_w067_capacity_day
from . import test_w034_raise_eco_from_wo
from . import test_w040_report_problem_wizard
from . import test_w080_tab_consolidation
from . import test_w087_shift_handover_structured
from . import test_w090_scrap_ncr_backlink
