apiVersion: v1
kind: Service
metadata:
  name: {{ include "kitchenforge.fullname" . }}-pg
  labels:
    {{- include "kitchenforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "kitchenforge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
