apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kitchenforge.fullname" . }}-secrets
  labels:
    {{- include "kitchenforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
  ADMIN_PASSWD: {{ required "secrets.adminPasswd is required" .Values.secrets.adminPasswd | quote }}
