# SPDX-License-Identifier: LGPL-3.0-only
"""Guards the security fix: the Sysadmin course embeds real infrastructure
detail (SSH hosts, internal IP, backup paths) and must NOT be browsable or
self-enrollable by portal/connected users. Because the course XML is
regenerated by scripts/build_data_xml.py, this test catches a regression that
re-widens the visibility.
"""
from odoo.tests.common import TransactionCase, tagged


@tagged("post_install", "-at_install", "southbrook_elearning_internal")
class TestElearningSecurity(TransactionCase):

    def test_sysadmin_course_is_members_and_invite_only(self):
        course = self.env.ref("southbrook_elearning_internal.course_sysadmin")
        self.assertEqual(
            course.visibility, "members",
            "Sysadmin course exposes infrastructure detail — must be "
            "members-only, not 'connected' (which includes portal logins).")
        self.assertEqual(
            course.enroll, "invite",
            "Sysadmin course must be invite-only, not self-enrollable.")
